<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <div>
    <label><?php echo $this->__('CPF') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('CPF') ?>" name="payment[cpf]" value="<?php echo $this->htmlEscape($this->getInfoData('cpf')) ?>" />
    </span>
  </div>
  <div>
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>